[package]
name = "day-25"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aoc-runner = { path = "../aoc-runner" }
itertools = "0.12.0"
hashbrown = "0.14.3"
